### ISSUE TITLE
Capacitor in wrong place?

### ISSUE THREAD

**Issue by SukkoPera** [hackup/SD2IECplug#1]
Hi, thanks for sharing this nice project. I had a look at it and I think that the way C3 is connected doesn't make much sense, could you please check?

On the same topic, may I ask why you deemed it necessary to put a current-limiting resistor on the SD power rail (R15)?

Thanks for your time :).

**Comment by hackup** [comment]
Thanks for your feedback! I just had a quick look and it really seems that C3 is connected the wrong way in v2.0. It was still correct in the previous release v0.9. I will look closer and supply an updated version.

As noted in the project description, most of the schematic is taken from Shadowolf's design. If I recall correctly, there are some SD cards that will draw too much power on startup and R15 is meant to prevent this. I'll try to find the source for this and get back to you if I do.

**Comment by hackup** [comment]
I think I found the post regarding the current-limiting resistor:
https://www.forum64.de/index.php?thread/53167-sd2iec-v1-2-shadowolf/&postID=746897#post746897

R15 here is the same as R20 in the original schematic. It seems that there are some cards which cause such a high inrush current that the MCU resets when the card is inserted while the device is powered on.

**Comment by SukkoPera** [comment]
Thanks a lot! Unfortunately I had already removed it from my fork and I'm too lazy to add it back. Never mind, I am not too interested in changing the card while the device is powered on.
